// SEARCH BAR AREA
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_TAGS_TERMS = 'SET_TAGS_TERMS';
export const SET_MARKET_STATUS = 'SET_MARKET_STATUS';
export const SET_MARKET_REALTIME_STATUS = 'SET_MARKET_REALTIME_STATUS';
export const SET_STOCK_STATUS = 'SET_STOCK_STATUS';

// TESTING API CALLS
export const TEST_API_REQUEST = 'TEST_API_REQUEST';
export const TEST_API_RECEIVE = 'TEST_API_RECEIVE';