export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const FETCH_API_BEGIN = 'FETCH_API_BEGIN';
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE';
