export const PROTECTED_API_KEY = process.env.REACT_APP_CLOUD_IEX_API_KEY;
export const PROTECTED_API_URL = process.env.REACT_APP_CLOUD_IEX_API_URL;
export const UNPROTECTED_API_URL = process.env.REACT_APP_BASIC_IEX_API_URL;
